# Generated by Django 5.2.7 on 2025-10-27 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_skills_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='original_resume_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
