# Generated by Django 5.2.7 on 2025-10-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_original_resume_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='years_of_experience',
        ),
        migrations.AddField(
            model_name='profile',
            name='employment_type_preference',
            field=models.CharField(blank=True, default='FULLTIME,CONTRACTOR', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='experience_level_preference',
            field=models.CharField(blank=True, default='Any', max_length=50, null=True),
        ),
    ]
