# Generated by Django 5.2.7 on 2025-10-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_profile_years_of_experience_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='employment_type_preference',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='experience_level_preference',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='original_resume_filename',
        ),
        migrations.AddField(
            model_name='profile',
            name='years_of_experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
