# Generated by Django 5.2.7 on 2025-10-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_profile_employment_type_preference_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='years_of_experience',
        ),
        migrations.AddField(
            model_name='profile',
            name='employment_type_preference',
            field=models.CharField(blank=True, default='FULLTIME,CONTRACTOR', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='experience_level_preference',
            field=models.CharField(blank=True, default='Any', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='original_resume_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
